version: 2
jobs:
  build-buildpack:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: Check that all the languages interlock
          command: ./check.bat
  build-node:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Check that all the languages interlock
          command: ./check.bat

