version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    macos:
      xcode: "8.3.3"
    steps:
      - checkout
      - run:
          name: Check that all the languages interlock
          command: ./check.bat
