version: 2
jobs:
  build-buildpack:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Check that all the languages interlock
          command: ./check.bat
  build-node:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Check that all the languages interlock
          command: ./check.bat
workflows:
  version: 2
  build:
    jobs:
      - build-buildpack
      - build-node
